### ISSUE TITLE
please add .caja-extension file

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-user-share#26]
Like it's done in the caja-extensions repo.

**Comment by infirit** [comment]
I can't test test this atm so can you try https://github.com/infirit/mate-user-share/commit/d0939b63618ae97d417cb8a0e677ea2010bda5a0 and let me know if it works ok. 

Also, feel free to suggest a better description :smile:

**Comment by monsta** [comment]
I seem to have problems fetching this branch...

**Comment by infirit** [comment]
I pushed the ``ini`` branch to the main repo. Hope this works for you.

**Comment by monsta** [comment]
Yes, now it's ok... I just can't see the proper about window in Caja's extensions dialog. Same for caja-dropbow BTW.

**Comment by monsta** [comment]
Ah, now I know why... I think the ```.caja-extension``` file should have the same name as the ```.so``` file.
But instead we have:
```
/usr/lib/x86_64-linux-gnu/caja/extensions-2.0/libcaja-share-extension.so
/usr/share/caja/extensions/libcaja-user-share.caja-extension
```

**Comment by monsta** [comment]
@infirit: solved that in https://github.com/mate-desktop/mate-user-share/pull/27

**Comment by infirit** [comment]
Merged the branches and pushed.
